# Generated by Django 2.2.7 on 2020-09-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=None,
                                       null=True,
                                       verbose_name='expiration date'),
        ),
    ]
